name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy data
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get Commit Hash
        id: commit
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            paschendale/las-to-3dtiles:latest
            paschendale/las-to-3dtiles:sha-${{ steps.commit.outputs.COMMIT_HASH }}
